BEGIN;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "profile" (
    "id" UUID NOT NULL UNIQUE PRIMARY KEY,
    "email" VARCHAR (100) NOT NULL UNIQUE,
    "full_name" VARCHAR (150) NOT NULL,
    "phone_number" VARCHAR (15) NOT NULL UNIQUE,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMP(3) NOT NULL DEFAULT NOW()
);

COMMIT;
