BEGIN;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "profile" (
    "profileID" UUID NOT NULL UNIQUE PRIMARY KEY,
    "email" VARCHAR (100) NOT NULL UNIQUE,
    "fullName" VARCHAR (150) NOT NULL,
    "phoneNumber" VARCHAR (15) NOT NULL UNIQUE,
    "createdAT" TIMESTAMP(3) NOT NULL DEFAULT NOW()
);

COMMIT;
