{
 "title": "Profile Service",
 "description": "Total HTTP requests per method and status in the last 1 minute.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kafka Produce Delivery Results",
   "type": "barchart",
   "description": "Delivery success/failure counts per topic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (topic, status) (rate(fitrang_profile_service_kafka_produce_delivery_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "state-timeline",
   "description": "95th percentile latency per HTTP method.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, method) (rate(fitrang_profile_service_http_request_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Produce Enqueued",
   "type": "barchart",
   "description": "Messages successfully enqueued per topic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (topic) (rate(fitrang_profile_service_kafka_produce_enqueued_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Total",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (method, status) (rate(fitrang_profile_service_http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GraphQL Operation Duration",
   "type": "timeseries",
   "description": "95th percentile latency per GraphQL operation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, operation, type) (rate(fitrang_profile_service_graphql_operation_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC Request Duration",
   "type": "timeseries",
   "description": "95th percentile latency per gRPC method",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, method) (rate(fitrang_profile_service_grpc_request_duration_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC Requests Total",
   "type": "timeseries",
   "description": "Total gRPC requests per method and status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (method, status) (rate(fitrang_profile_service_grpc_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}