package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/Foxtrot-14/FitRang/profile-service/graph/model"
)

// RequestAccess is the resolver for the requestAccess field.
func (r *mutationResolver) RequestAccess(ctx context.Context, username string) (bool, error) {
	return r.AccessService.RequestAccess(ctx, username)
}

// GrantAccess is the resolver for the grantAccess field.
func (r *mutationResolver) GrantAccess(ctx context.Context, username string) (bool, error) {
	return r.AccessService.GrantAccess(ctx, username)
}

// CreateProfile is the resolver for the createProfile field.
func (r *mutationResolver) CreateProfile(ctx context.Context, input model.ProfileCreateInput) (*model.Profile, error) {
	return r.ProfileService.CreateProfile(ctx, input)
}

// CreateDossier is the resolver for the createDossier field.
func (r *mutationResolver) CreateDossier(ctx context.Context, input model.CreateDossier) (*model.Dossier, error) {
	return r.DossierService.CreateDossier(ctx, input)
}

// UpdateDossier is the resolver for the updateDossier field.
func (r *mutationResolver) UpdateDossier(ctx context.Context, input model.UpdateDossier) (*model.Dossier, error) {
	return r.DossierService.UpdateDossier(ctx, input)
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.ProfileUpdateInput) (*model.Profile, error) {
	return r.ProfileService.UpdateProfile(ctx, input)
}

// UploadProfilePicture is the resolver for the uploadProfilePicture field.
func (r *mutationResolver) UploadProfilePicture(ctx context.Context, file graphql.Upload) (*model.Profile, error) {
	return r.ProfileService.UploadProfile(ctx, file)
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context, username string) (*model.Profile, error) {
	return r.ProfileService.GetProfile(ctx, username)
}

// GetMyProfile is the resolver for the getMyProfile field.
func (r *queryResolver) GetMyProfile(ctx context.Context) (*model.Profile, error) {
	return r.ProfileService.GetMyProfile(ctx)
}

// GetMyDossier is the resolver for the getMyDossier field.
func (r *queryResolver) GetMyDossier(ctx context.Context) (*model.Dossier, error) {
	return r.DossierService.GetMyDossier(ctx)
}

// Dossier is the resolver for the dossier field.
func (r *queryResolver) Dossier(ctx context.Context, username string) (*model.Dossier, error) {
	return r.DossierService.GetDossier(ctx, username)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
