// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateDossier struct {
	FaceType        string   `json:"faceType"`
	SkinTone        SkinTone `json:"skinTone"`
	BodyType        string   `json:"bodyType"`
	Gender          Gender   `json:"gender"`
	PreferredColors []string `json:"preferredColors,omitempty"`
	DislikedColors  []string `json:"dislikedColors,omitempty"`
	Height          *string  `json:"height,omitempty"`
	Weight          *string  `json:"weight,omitempty"`
}

type Dossier struct {
	ID              string   `json:"id"`
	Email           string   `json:"email"`
	Username        string   `json:"username"`
	FaceType        string   `json:"faceType"`
	SkinTone        SkinTone `json:"skinTone"`
	BodyType        string   `json:"bodyType"`
	Gender          Gender   `json:"gender"`
	PreferredColors []string `json:"preferredColors,omitempty"`
	DislikedColors  []string `json:"dislikedColors,omitempty"`
	Viewers         []string `json:"viewers"`
	Height          *string  `json:"height,omitempty"`
	Weight          *string  `json:"weight,omitempty"`
	CreatedAt       string   `json:"createdAt"`
	UpdatedAt       string   `json:"updatedAt"`
}

type Mutation struct {
}

type Profile struct {
	ID           string       `json:"id"`
	FullName     string       `json:"fullName"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	AccessStatus AccessStatus `json:"accessStatus"`
	ProfileURL   *string      `json:"profileUrl,omitempty"`
	CreatedAt    string       `json:"createdAt"`
	UpdatedAt    string       `json:"updatedAt"`
}

type ProfileCreateInput struct {
	FullName string `json:"fullName"`
	Email    string `json:"email"`
	Username string `json:"username"`
}

type ProfileUpdateInput struct {
	Email    string  `json:"email"`
	Username string  `json:"username"`
	FullName *string `json:"fullName,omitempty"`
}

type Query struct {
}

type UpdateDossier struct {
	FaceType        *string   `json:"faceType,omitempty"`
	SkinTone        *SkinTone `json:"skinTone,omitempty"`
	BodyType        *string   `json:"bodyType,omitempty"`
	Gender          *Gender   `json:"gender,omitempty"`
	PreferredColors []*string `json:"preferredColors,omitempty"`
	DislikedColors  []*string `json:"dislikedColors,omitempty"`
	Height          *string   `json:"height,omitempty"`
	Weight          *string   `json:"weight,omitempty"`
}

type AccessStatus string

const (
	AccessStatusYes       AccessStatus = "YES"
	AccessStatusNo        AccessStatus = "NO"
	AccessStatusRequested AccessStatus = "REQUESTED"
	AccessStatusOwner     AccessStatus = "OWNER"
)

var AllAccessStatus = []AccessStatus{
	AccessStatusYes,
	AccessStatusNo,
	AccessStatusRequested,
	AccessStatusOwner,
}

func (e AccessStatus) IsValid() bool {
	switch e {
	case AccessStatusYes, AccessStatusNo, AccessStatusRequested, AccessStatusOwner:
		return true
	}
	return false
}

func (e AccessStatus) String() string {
	return string(e)
}

func (e *AccessStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccessStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccessStatus", str)
	}
	return nil
}

func (e AccessStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccessStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccessStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Gender string

const (
	GenderMale   Gender = "male"
	GenderFemale Gender = "female"
)

var AllGender = []Gender{
	GenderMale,
	GenderFemale,
}

func (e Gender) IsValid() bool {
	switch e {
	case GenderMale, GenderFemale:
		return true
	}
	return false
}

func (e Gender) String() string {
	return string(e)
}

func (e *Gender) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Gender(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Gender", str)
	}
	return nil
}

func (e Gender) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Gender) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Gender) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SkinTone string

const (
	SkinTonePale  SkinTone = "pale"
	SkinToneLight SkinTone = "light"
	SkinToneOlive SkinTone = "olive"
	SkinToneDark  SkinTone = "dark"
)

var AllSkinTone = []SkinTone{
	SkinTonePale,
	SkinToneLight,
	SkinToneOlive,
	SkinToneDark,
}

func (e SkinTone) IsValid() bool {
	switch e {
	case SkinTonePale, SkinToneLight, SkinToneOlive, SkinToneDark:
		return true
	}
	return false
}

func (e SkinTone) String() string {
	return string(e)
}

func (e *SkinTone) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SkinTone(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SkinTone", str)
	}
	return nil
}

func (e SkinTone) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SkinTone) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SkinTone) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
