// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: profile_dossier.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessStatus int32

const (
	AccessStatus_ACCESS_STATUS_UNSPECIFIED AccessStatus = 0
	AccessStatus_ACCESS_STATUS_PENDING     AccessStatus = 1
	AccessStatus_ACCESS_STATUS_GRANTED     AccessStatus = 2
	AccessStatus_ACCESS_STATUS_REVOKED     AccessStatus = 3
)

// Enum value maps for AccessStatus.
var (
	AccessStatus_name = map[int32]string{
		0: "ACCESS_STATUS_UNSPECIFIED",
		1: "ACCESS_STATUS_PENDING",
		2: "ACCESS_STATUS_GRANTED",
		3: "ACCESS_STATUS_REVOKED",
	}
	AccessStatus_value = map[string]int32{
		"ACCESS_STATUS_UNSPECIFIED": 0,
		"ACCESS_STATUS_PENDING":     1,
		"ACCESS_STATUS_GRANTED":     2,
		"ACCESS_STATUS_REVOKED":     3,
	}
)

func (x AccessStatus) Enum() *AccessStatus {
	p := new(AccessStatus)
	*p = x
	return p
}

func (x AccessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_dossier_proto_enumTypes[0].Descriptor()
}

func (AccessStatus) Type() protoreflect.EnumType {
	return &file_profile_dossier_proto_enumTypes[0]
}

func (x AccessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessStatus.Descriptor instead.
func (AccessStatus) EnumDescriptor() ([]byte, []int) {
	return file_profile_dossier_proto_rawDescGZIP(), []int{0}
}

type GetByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByEmailRequest) Reset() {
	*x = GetByEmailRequest{}
	mi := &file_profile_dossier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByEmailRequest) ProtoMessage() {}

func (x *GetByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_dossier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetByEmailRequest) Descriptor() ([]byte, []int) {
	return file_profile_dossier_proto_rawDescGZIP(), []int{0}
}

func (x *GetByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetByUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByUsernameRequest) Reset() {
	*x = GetByUsernameRequest{}
	mi := &file_profile_dossier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByUsernameRequest) ProtoMessage() {}

func (x *GetByUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_dossier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByUsernameRequest.ProtoReflect.Descriptor instead.
func (*GetByUsernameRequest) Descriptor() ([]byte, []int) {
	return file_profile_dossier_proto_rawDescGZIP(), []int{1}
}

func (x *GetByUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       []*Profile             `protobuf:"bytes,1,rep,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfilesResponse) Reset() {
	*x = GetProfilesResponse{}
	mi := &file_profile_dossier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesResponse) ProtoMessage() {}

func (x *GetProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_dossier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesResponse.ProtoReflect.Descriptor instead.
func (*GetProfilesResponse) Descriptor() ([]byte, []int) {
	return file_profile_dossier_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfilesResponse) GetProfile() []*Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetDossierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dossier       *Dossier               `protobuf:"bytes,1,opt,name=dossier,proto3" json:"dossier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDossierResponse) Reset() {
	*x = GetDossierResponse{}
	mi := &file_profile_dossier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDossierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDossierResponse) ProtoMessage() {}

func (x *GetDossierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_dossier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDossierResponse.ProtoReflect.Descriptor instead.
func (*GetDossierResponse) Descriptor() ([]byte, []int) {
	return file_profile_dossier_proto_rawDescGZIP(), []int{3}
}

func (x *GetDossierResponse) GetDossier() *Dossier {
	if x != nil {
		return x.Dossier
	}
	return nil
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	AccessStatus  AccessStatus           `protobuf:"varint,5,opt,name=access_status,json=accessStatus,proto3,enum=profile.AccessStatus" json:"access_status,omitempty"`
	ProfileUrl    string                 `protobuf:"bytes,6,opt,name=profile_url,json=profileUrl,proto3" json:"profile_url,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_profile_dossier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_profile_dossier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_profile_dossier_proto_rawDescGZIP(), []int{4}
}

func (x *Profile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Profile) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Profile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Profile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Profile) GetAccessStatus() AccessStatus {
	if x != nil {
		return x.AccessStatus
	}
	return AccessStatus_ACCESS_STATUS_UNSPECIFIED
}

func (x *Profile) GetProfileUrl() string {
	if x != nil {
		return x.ProfileUrl
	}
	return ""
}

func (x *Profile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Profile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Dossier struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username        string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	FaceType        string                 `protobuf:"bytes,4,opt,name=face_type,json=faceType,proto3" json:"face_type,omitempty"`
	SkinTone        string                 `protobuf:"bytes,5,opt,name=skin_tone,json=skinTone,proto3" json:"skin_tone,omitempty"`
	BodyType        string                 `protobuf:"bytes,6,opt,name=body_type,json=bodyType,proto3" json:"body_type,omitempty"`
	Gender          string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	PreferredColors []string               `protobuf:"bytes,8,rep,name=preferred_colors,json=preferredColors,proto3" json:"preferred_colors,omitempty"`
	DislikedColors  []string               `protobuf:"bytes,9,rep,name=disliked_colors,json=dislikedColors,proto3" json:"disliked_colors,omitempty"`
	Viewers         []string               `protobuf:"bytes,10,rep,name=viewers,proto3" json:"viewers,omitempty"`
	Height          string                 `protobuf:"bytes,11,opt,name=height,proto3" json:"height,omitempty"`
	Weight          string                 `protobuf:"bytes,12,opt,name=weight,proto3" json:"weight,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Dossier) Reset() {
	*x = Dossier{}
	mi := &file_profile_dossier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dossier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dossier) ProtoMessage() {}

func (x *Dossier) ProtoReflect() protoreflect.Message {
	mi := &file_profile_dossier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dossier.ProtoReflect.Descriptor instead.
func (*Dossier) Descriptor() ([]byte, []int) {
	return file_profile_dossier_proto_rawDescGZIP(), []int{5}
}

func (x *Dossier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dossier) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Dossier) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Dossier) GetFaceType() string {
	if x != nil {
		return x.FaceType
	}
	return ""
}

func (x *Dossier) GetSkinTone() string {
	if x != nil {
		return x.SkinTone
	}
	return ""
}

func (x *Dossier) GetBodyType() string {
	if x != nil {
		return x.BodyType
	}
	return ""
}

func (x *Dossier) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Dossier) GetPreferredColors() []string {
	if x != nil {
		return x.PreferredColors
	}
	return nil
}

func (x *Dossier) GetDislikedColors() []string {
	if x != nil {
		return x.DislikedColors
	}
	return nil
}

func (x *Dossier) GetViewers() []string {
	if x != nil {
		return x.Viewers
	}
	return nil
}

func (x *Dossier) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *Dossier) GetWeight() string {
	if x != nil {
		return x.Weight
	}
	return ""
}

func (x *Dossier) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Dossier) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_profile_dossier_proto protoreflect.FileDescriptor

const file_profile_dossier_proto_rawDesc = "" +
	"\n" +
	"\x15profile_dossier.proto\x12\aprofile\")\n" +
	"\x11GetByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"2\n" +
	"\x14GetByUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"A\n" +
	"\x13GetProfilesResponse\x12*\n" +
	"\aprofile\x18\x01 \x03(\v2\x10.profile.ProfileR\aprofile\"@\n" +
	"\x12GetDossierResponse\x12*\n" +
	"\adossier\x18\x01 \x01(\v2\x10.profile.DossierR\adossier\"\x83\x02\n" +
	"\aProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12:\n" +
	"\raccess_status\x18\x05 \x01(\x0e2\x15.profile.AccessStatusR\faccessStatus\x12\x1f\n" +
	"\vprofile_url\x18\x06 \x01(\tR\n" +
	"profileUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\x96\x03\n" +
	"\aDossier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1b\n" +
	"\tface_type\x18\x04 \x01(\tR\bfaceType\x12\x1b\n" +
	"\tskin_tone\x18\x05 \x01(\tR\bskinTone\x12\x1b\n" +
	"\tbody_type\x18\x06 \x01(\tR\bbodyType\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\x12)\n" +
	"\x10preferred_colors\x18\b \x03(\tR\x0fpreferredColors\x12'\n" +
	"\x0fdisliked_colors\x18\t \x03(\tR\x0edislikedColors\x12\x18\n" +
	"\aviewers\x18\n" +
	" \x03(\tR\aviewers\x12\x16\n" +
	"\x06height\x18\v \x01(\tR\x06height\x12\x16\n" +
	"\x06weight\x18\f \x01(\tR\x06weight\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt*~\n" +
	"\fAccessStatus\x12\x1d\n" +
	"\x19ACCESS_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACCESS_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15ACCESS_STATUS_GRANTED\x10\x02\x12\x19\n" +
	"\x15ACCESS_STATUS_REVOKED\x10\x032\x82\x02\n" +
	"\x0eProfileService\x12N\n" +
	"\x12GetProfilesByEmail\x12\x1a.profile.GetByEmailRequest\x1a\x1c.profile.GetProfilesResponse\x12L\n" +
	"\x11GetDossierByEmail\x12\x1a.profile.GetByEmailRequest\x1a\x1b.profile.GetDossierResponse\x12R\n" +
	"\x14GetDossierByUsername\x12\x1d.profile.GetByUsernameRequest\x1a\x1b.profile.GetDossierResponseB;Z9github.com/Foxtrot-14/FitRang/profile-service/proto;protob\x06proto3"

var (
	file_profile_dossier_proto_rawDescOnce sync.Once
	file_profile_dossier_proto_rawDescData []byte
)

func file_profile_dossier_proto_rawDescGZIP() []byte {
	file_profile_dossier_proto_rawDescOnce.Do(func() {
		file_profile_dossier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_dossier_proto_rawDesc), len(file_profile_dossier_proto_rawDesc)))
	})
	return file_profile_dossier_proto_rawDescData
}

var file_profile_dossier_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_profile_dossier_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_profile_dossier_proto_goTypes = []any{
	(AccessStatus)(0),            // 0: profile.AccessStatus
	(*GetByEmailRequest)(nil),    // 1: profile.GetByEmailRequest
	(*GetByUsernameRequest)(nil), // 2: profile.GetByUsernameRequest
	(*GetProfilesResponse)(nil),  // 3: profile.GetProfilesResponse
	(*GetDossierResponse)(nil),   // 4: profile.GetDossierResponse
	(*Profile)(nil),              // 5: profile.Profile
	(*Dossier)(nil),              // 6: profile.Dossier
}
var file_profile_dossier_proto_depIdxs = []int32{
	5, // 0: profile.GetProfilesResponse.profile:type_name -> profile.Profile
	6, // 1: profile.GetDossierResponse.dossier:type_name -> profile.Dossier
	0, // 2: profile.Profile.access_status:type_name -> profile.AccessStatus
	1, // 3: profile.ProfileService.GetProfilesByEmail:input_type -> profile.GetByEmailRequest
	1, // 4: profile.ProfileService.GetDossierByEmail:input_type -> profile.GetByEmailRequest
	2, // 5: profile.ProfileService.GetDossierByUsername:input_type -> profile.GetByUsernameRequest
	3, // 6: profile.ProfileService.GetProfilesByEmail:output_type -> profile.GetProfilesResponse
	4, // 7: profile.ProfileService.GetDossierByEmail:output_type -> profile.GetDossierResponse
	4, // 8: profile.ProfileService.GetDossierByUsername:output_type -> profile.GetDossierResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_profile_dossier_proto_init() }
func file_profile_dossier_proto_init() {
	if File_profile_dossier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_dossier_proto_rawDesc), len(file_profile_dossier_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_dossier_proto_goTypes,
		DependencyIndexes: file_profile_dossier_proto_depIdxs,
		EnumInfos:         file_profile_dossier_proto_enumTypes,
		MessageInfos:      file_profile_dossier_proto_msgTypes,
	}.Build()
	File_profile_dossier_proto = out.File
	file_profile_dossier_proto_goTypes = nil
	file_profile_dossier_proto_depIdxs = nil
}
